kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: janus
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.4
          args:
            - --api.insecure
            - --accesslog=true
            - --providers.kubernetesingress
            - --metrics.prometheus=true
            - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
