kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: janus
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.4
          args:
            - --entrypoints.websecure.http.tls.certresolver=cloudflare
            - --entrypoints.websecure.http.tls.domains[0].main=${JANUS_HOSTNAME}
            - --entrypoints.websecure.http.tls.domains[0].sans=*.${JANUS_HOSTNAME}
            - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.cloudflare.acme.email=mail@${JANUS_HOSTNAME}
            - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
            - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
          ports:
            - name: web
              containerPort: 80
              redirectTo: 443
            - name: dashboard
              containerPort: 8080
            - name: websecure
              containerPort: 443
          env:
            - name: CF_API_EMAIL
              valueFrom:
                secretKeyRef:
                  key: email
                  name: cloudflare-api-credentials
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  key: apiKey
                  name: cloudflare-api-credentials
# persistence:
#   enabled: true
#   path: /certs
#   size: 128Mi